server:
  port: 8090
spring:
  profiles:
    active: dev
    include: secret
  datasource:
    url: jdbc:mysql://stopnoise.c98mwioqyg18.ap-southeast-2.rds.amazonaws.com:3306/stopNoise?serverTimezone=UTC&characterEncoding=UTF-8
    username: stopNoise_admin
    password: ajtwoddltkwkcjfja
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
  logging:
    level:
      com.ll.demo03: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.orm.jdbc.bind: TRACE
      org.hibernate.orm.jdbc.extract: TRACE
      org.springframework.transaction: debug
      org.springframework.transaction.interceptor: TRACE
custom:
  site:
    name: "My Site"

gemini:
  api-key: "AIzaSyC6sd9IpfzQQeaWqJqm4Sk-CrVcjTj8T4Q"
