name: CI/CD with Docker and AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build --exclude-task test

      # --- Docker 관련 추가 단계 ---
      # Docker 이미지 빌드 및 Docker Hub 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/stopnoise-app:latest

      # --- SSH를 통한 EC2 배포 단계 ---
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 기존 Docker 컨테이너 중지 및 삭제
            docker stop stopnoise-container || true
            docker rm stopnoise-container || true

            # Docker Hub에서 최신 이미지 받기
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/stopnoise-app:latest

            # 새로운 Docker 컨테이너 실행
            docker run -d --name stopnoise-container -p 8090:8090 ${{ secrets.DOCKERHUB_USERNAME }}/stopnoise-app:latest